### ISSUE TITLE
playsound import

### ISSUE THREAD

**Issue by findthebug** [Rytis-J/Dexcom-Follow#2]
looks like playsound is not preinstalled on mac so you need to do it manual. 

`
File "/Users/home/dexcomfollow/mydata.py", line 4, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'
`

Installed https://pypi.org/project/playsound/ but no luck

**Comment by Rytis-J** [comment]
Hello, thank you for bringing this to my attention. In order for the sound to work, please run these 2 commands, depending on your pip choose the one that you use:

`pip3 install playsound` or `pip install playsound`
`pip3 install PyObjC` or `pip install PyObjC`

This should fix the underlining problem. I will roll out a new version with the issue fix later today.

**Comment by Rytis-J** [comment]
I addressed your issue, and rolled out an update. Should work well now. Again, thanks for bringing this to my attention.
