### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by saddexcomuser** [Rytis-J/Dexcom-Follow#3]
hello, i made a github account just to say this so maybe this is a dumb question, but i followed all the steps, and i got to the screen with the big block text. but it says username and password are incorrect, even when i enter them again. i use this username and password to log in to dexcom clarity so they are definitely correct. am i missing something? (censored image included)
![Screenshot 2023-12-28 154305](https://github.com/Rytis-J/Dexcom-Follow/assets/155109234/030bd1da-78f8-4d5f-9e7d-3d1c8e0880d3)

**Comment by Rytis-J** [comment]
Hey! By default Dexcom-Follow will only work for people outside the United States. In order for United States based accounts to work, make sure to set the region boolean to True. Let me know if this helps!
